org: haraguti2002
app: opnweather
service: opnweather
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-1
  profile: serverless-user

plugins:
  - serverless-offline

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
